security:
    encoders:
        AppBundle\Entity\Client:
            algorithm: bcrypt
    providers:
        entity_provider:
            entity:
                class: AppBundle:Client
                property: clientMame
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            pattern:  ^/login
            stateless: true
            anonymous: true
        register:
            pattern:  ^/register
            stateless: true
            anonymous: true

